language: node_js
node_js:
  - "stable"
  addons:
  code_climate:
    repo_token:
      secure: "dcbc5ef06fc1350dfb5f98a847056bf672bbf6b9f3fb4bd9207ba4bd4d4149b3"
script:
  - npm run test
after_success:
- npm run coveralls
- npm run coverage
